#ifndef ISPH_VERSION_H
#define ISPH_VERSION_H

#define ISPH_VERSION_STRING		"0.2.5"
#define ISPH_VERSION			25
#define ISPH_MAJOR_VERSION		(ISPH_VERSION / 100)
#define ISPH_MINOR_VERSION		((ISPH_VERSION % 100) / 10)
#define ISPH_SUBMINOR_VERSION	(ISPH_VERSION % 10)

#endif
